### ISSUE TITLE
fatal error: concurrent map writes

### ISSUE THREAD

**Issue by kalbasit** [rs/xlog#18]
```
fatal error: concurrent map writes

goroutine 3765 [running]:
runtime.throw(0xcf6ade, 0x15)
        /usr/local/go/src/runtime/panic.go:596 +0x95 fp=0xc42098f828 sp=0xc42098f808
runtime.mapassign(0xc03600, 0xc4208f6030, 0xc42098f8f0, 0xba2b40)
        /usr/local/go/src/runtime/hashmap.go:499 +0x667 fp=0xc42098f8c8 sp=0xc42098f828
github.com/rs/xlog.(*logger).SetField(0xc4208f6000, 0xceccc8, 0xa, 0xba2b40, 0xc4202aa600)
        /go/src/github.com/rs/xlog/xlog.go:234 +0x66 fp=0xc42098f910 sp=0xc42098f8c8
```

**Comment by kalbasit** [comment]
we should either protect the logger with a mutex or use [`sync.Map`](https://godoc.org/sync#Map) with Go 1.9.

**Comment by iscander** [comment]
or provide a recommendation for best usage practice:
`logger.Infof("Format ...", arg1, arg2,...argN, xlog.F{"key": "value",..."keyM": "valueM"})`

**Comment by tomsid** [comment]
@rs could you confirm that it's a bug that should be fixed and not by design (for performance reasons)?

**Comment by kalbasit** [comment]
@rs we ended up with zerolog, this problem went away when we did that.

**Comment by tomsid** [comment]
Yeah, that could be a solution, thanks. But what about that issue? Is that something that should be fixed? If not it would be nice to document that behavior.

Unfortunately can't do it as it takes too much effort, but thanks for the recommendation.

**Comment by rs** [comment]
Generally, when something is not documented as thread safe, it is caller’s job to ensure safety.
